name: Scale tests

on:
  schedule:
    # Every weekday at 03:29 UTC, see https://crontab.guru/
    - cron: "29 3 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install graphviz
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install
        run: |
          python -m pip install --no-deps -e .

      - name: Copy lithops configuration template
        run: |
          cp $GITHUB_WORKSPACE/.github/workflows/.lithops_config.template $GITHUB_WORKSPACE/.github/workflows/.lithops_config

      - name: Configure lithops
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/.github/workflows/.lithops_config
        env:
          aws.access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws.secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        run: |
          python examples/lithops-add-random.py s3://cubed-tom-temp cubed-runtime
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LITHOPS_CONFIG_FILE: ${{ github.workspace }}/.github/workflows/.lithops_config

      - name: Save plots
        uses: actions/upload-artifact@v3
        with:
          name: plots
          path: plots/
